### ISSUE TITLE
Build success yet no generated PDF

### ISSUE THREAD

**Issue by justinsoon** [ShikherVerma/resume#5]
Receiving a successful build. Yet no complied PDF shows up in gh-pages branch.

**Comment by ShikherVerma** [comment]
Hmm somehow the `deploy.sh` script lost its execute permission https://travis-ci.org/justinsoon/resume#L971
Change the permission and commit again.
`chmod +x deploy.sh` should fix the permission.

**Comment by justinsoon** [comment]
Regenerated a new token. Changed perms and still getting the same issue.

**Comment by ShikherVerma** [comment]
oh you had to change the permission and commit again. Something like this:
```
chmod +x deploy.sh
git commit -m "Fixed permissions"
```
But instead you have changed the travis file to [change permission everytime instead of executing](https://github.com/justinsoon/resume/blob/master/.travis.yml#L16). That line use to start the deploy script.Please read the [output on travis-ci.org](https://travis-ci.org/justinsoon/resume).

**Comment by justinsoon** [comment]
Sorry, I'm not exactly sure on how to add the perms. So I did
```
before_install:
  - chmod +x deploy.sh 
```
In the .travis.yml

I'm not getting the denied perms anymore, but now I'm receiving a [no such file or directory](https://travis-ci.org/justinsoon/resume#L973) error.

I really appreciate you giving back to the community. Sorry for the hassle.

**Comment by ShikherVerma** [comment]
@justinsoon no worries mate! lets make it work :)
It looks like [windows messes up line endings](https://stackoverflow.com/questions/14219092/bash-my-script-bin-bashm-bad-interpreter-no-such-file-or-directory). I'll create a pull request to your repo after fixing the line endings.

**Comment by ShikherVerma** [comment]
![yaay](https://media.giphy.com/media/yoJC2GnSClbPOkV0eA/giphy.gif)

**Comment by justinsoon** [comment]
It worked! Thank you so much!
